### ISSUE TITLE
OSX binary would be easier to install and keep updated via brew

### ISSUE THREAD

**Issue by robdimsdale** [pivotal-cf-experimental/git-hooks-core#3]
The easiest way to install and update binaries on OSX is brew - remembering to periodically update the OSX binary is more error-prone.

Probably at the [pivotal-tap](https://github.com/pivotal/homebrew-tap) repository.

You can see how we automatically update the pivnet-cli [here](https://github.com/pivotal-cf/pivnet-resource-ci/tree/master/pivnet-cli/create-homebrew-formula).

**Comment by aramprice** [comment]
Adding brew support is something we are open to adding at some point. In the mean time the CLI has an `update` command which will self-update:

```
cred-alert-cli update
```

The CLI should also warn (on `stderr`) if it is out of date.

**Comment by robdimsdale** [comment]
That's very helpful and I didn't know that - thanks. That solves the problem of easily updating, but it doesn't solve the problem of initial discovery. That's fine though - the README describes how to download the binary. It's not as smooth as brew, but it's good enough. I'll close this issue now.
